#+TITLE: CMPUT 466 Assignment 2
#+AUTHOR: Arun Woosaree
#+OPTIONS: toc:nil num:nil
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_CLASS_OPTIONS: [letterpaper]
#+LATEX_HEADER: \theoremstyle{definition}
#+LATEX_HEADER: \newtheorem{definition}{Definition}[section]

#+begin_src elisp :exports none
(setq org-latex-listings 'minted
      org-latex-packages-alist '(("" "minted"))
      org-latex-minted-options '(("linenos" "true"))
      org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
#+end_src

#+RESULTS:
| pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f | pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f |

* Problem 1

** Part 1
\[\{(x_1, x_2): x_1^2 + x_2^2 = 1\}\]
This set is not convex.
\begin{proof}
Assume the set is convex.

Let's draw a line from \((x_1, x_2) = (-1, 0) \) to \( (1, 0)\)

These two points are part of the set because \((-1)^2 + 0^2 = 1\),

and \(1^2 + 0^2 = 1\)


That is,
\(x_1 \in [-1,1], x_2 =0 \)


If this set is convex, then any point on this line must also be in the set.

Let's select the point \((0, 0)\). i.e., \(\lambda = 0.5\)

This point is clearly part of the line defined above, however, it is definitely not
in the set because \(0^2 + 0^2 = 0 \neq 1\).

Therefore, we have found a counterexample that proves that this set is not convex.
\end{proof}
** Part 2
\[\{(x_1, x_2): |x_1| + |x_2| \leq 1\}\]

This set is convex.

We begin by looking at the definition:

let \(\mathbf{x}= \begin{pmatrix}x_1\\ x_2\end{pmatrix}, \mathbf{y}= \begin{pmatrix}y_1\\ y_2\end{pmatrix} \) be any two points in the set.

Using the definition, if the set is convex, then

\[\lambda x + (1-\lambda) y, \lambda \in (0, 1) \]

is also in the set.

Applying this definition, we get the point:

\[ \begin{pmatrix}
\lambda x_1 + (1-\lambda) y_1 \\
\lambda x_2 + (1-\lambda) y_2
\end{pmatrix} \]

If this point is in the set, we need to prove that:

\[ |\lambda x_1 + (1-\lambda) y_1| + |\lambda x_2 + (1-\lambda) y_2| \leq 1 \]

\begin{proof}
Using the triangle inequality: \(|x+y| \leq |x| + |y|\):

\[ |\lambda x_1 + (1-\lambda) y_1| + |\lambda x_2 + (1-\lambda) y_2| \leq
|\lambda x_1| + |(1-\lambda) y_1| + |\lambda x_2| + |(1-\lambda)y_2| \]


we can factor out \(\lambda\) and \((1-\lambda)\) from the right side, because by definition, \(\lambda \in (0, 1)\):

\[\lambda (|x_1| + |x_2|) + (1-\lambda) (|y_1| + |y_2|) \]

Because \textbf{x} and \textbf{y} are in the set, we know that:
\[ |x_1| + |x_2| \leq 1\]
\[|y_1| + |y_2| \leq 1\]

Because of the above and \(\lambda \in (0,1)\), we also know that:
\[
\lambda (\dots) + (1-\lambda) (\dots) \leq 1
\]
(The values where the dots are were determined to be \(\leq 1\))



Thus,
\[\lambda (|x_1| + |x_2|) + (1-\lambda) (|y_1| + |y_2|) \leq 1\]

And because:
\[ |\lambda x_1 + (1-\lambda) y_1| + |\lambda x_2 + (1-\lambda) y_2| \leq
\lambda (|x_1| + |x_2|) + (1-\lambda) (|y_1| + |y_2|) \leq 1\]

We have finally proven that:
\[ |\lambda x_1 + (1-\lambda) y_1| + |\lambda x_2 + (1-\lambda) y_2| \leq 1 \]

, which means that the set is indeed convex.

\end{proof}

* Problem 2
\[f(x_1, x_2) = x_1^2 + x_2^2 - 4x_1x_2\]
** a) \(x_1\) variable, \(x_2\) constant:
\[\nabla^2 f(x_1) = \nabla 2x_1 - 4x_2\]
\[= 2 \geq 0\]

Because the second order gradient of \(f(x_1, x_2)\) is positive when \(x_2\) is constant, we have determined that
\(f\) is convex in \(x_1\)
** b) \(x_2\) variable, \(x_1\) constant
\[\nabla^2 f(x_2) = \nabla 2x_2 - 4x_1\]
\[= 2 \geq 0\]
Because the second order gradient of \(f(x_1, x_2)\) is positive when \(x_1\) is constant, we have determined that
\(f\) is convex in \(x_2\)
** c) \(f: \mathbb{R}^2 \to \mathbb{R}\)
#+begin_src python :exports both :results output verbatim
import numpy as np
from numpy import linalg as LA
# in a) and b) we found the values 2 and 2 in the Hessian matrix
# -4 is obtained because del/ (del x_1 del_x2) f(x_1, x_2) = -4
# same for del/ (del x_2 del_x1) because the matrix is symmetric
H = np.array([
    [2, -4],
    [-4, 2]
            ])
eigenval, eigenvec = LA.eig(H)
print(f"eigenval: {eigenval} | eigenvector: {eigenvec} ")

if any(map(lambda x: x < 0, eigenval)):
    print("Because one of the eigenvalues are negative, we conclude that the function is not convex")
else:
    print("Because all of the eigenvalues are positive, we conclude that the function is convex")
#+end_src

#+RESULTS:
: eigenval: [ 6. -2.] | eigenvector: [[ 0.70710678  0.70710678]
:  [-0.70710678  0.70710678]]
: Because one of the eigenvalues are negative, we conclude that the function is not convex
* Problem 3
If \(f\) is a differentiable convex function, then \(f\) satisfies the first-order condition
\begin{proof}

Given \(f\) is a differentiable convex function, the definition holds:

\[\forall x, y \in dom f, \forall \lambda \in (0, 1), f(\lambda x + (1-\lambda)y) \leq \lambda f(x) + (1-\lambda) f(y)\]

Let's do some re-arranging:

\[f(\lambda x + y - \lambda y)) \leq \lambda f(x) + f(y) - \lambda f(y) \]

\[f(\lambda (x-y) + y)] \leq \lambda (f(x) - f(y)) + f(y)\]

\[\Rightarrow \frac{f(\lambda (x-y) + y) - f(y)}{\lambda} \leq f(x) - f(y)\]

The left side of this equation looks exactly like the definition of the derivative using limits.

As \(\lambda \to 0\),
\[\Rightarrow \nabla [f(y)]^T (x-y) \leq f(x) - f(y)\]
\[ \nabla [f(y)]^T (x-y) + f(y) \leq f(x)\]

This is equivalent to the first-order condition:
\[f(y) \geq f(x) + \nabla [f(x)]^\top (y-x), \forall x, y \in dom f\]


\end{proof}
*
